### ISSUE TITLE
File Structure Design

### ISSUE THREAD

**Issue by HyeockJinKim** [0-Auth/0Auth#12]
## Feature Request
```
0Auth
├─ ...
└─ packages
        └─ client
        │       └─ src : client implementation for 0Auth
        │       └─ package.json
        └─ server
        │       └─ src : server implementation for 0Auth
        │       └─ package.json
        └─ message
                └─ src : message for client & server for 0Auth
                └─ package.json
```

All implementations should be written by `function`, not by `class`.

### client

* `host` setting
    - set server's url

* `signup` feature
    - register user information

* `verify` feature
    - using verify feature from `message`

* `update` feature
    - update user information

### server

* `secret key & public key` setting
    - manage server's pk and sk

* `signing` feature
    - The signging functions will be implemented separately by each message types.

* `signature verfication` feature
    - using verify feature from `message`

* `request` feature
    - request user's signed data

### message

* `Type` setting
    - enum Type : `Privacy`, `Trusted` and `Local`

* `signature` and `message vector` setting
    - using `SHA256` Hash and `AES` encryption from `cryptojs` library
    - using `EDDSA(ed25519)` Signature from `elliptic` library

* `verify` feature
    - The verification functions will be implemented separately by each message types.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by HyeockJinKim** [comment]
## Functions to export from @0auth/client.

* ```javascript
  aysnc function register_info(url: string, properties: Property[]): Promise<> {
    // TODO: Not implemented yet.
  }
  ```
    - A function that sends the client's information to the server and receives the server's signature when the value is correct.
    - But, I am not sure if this function must be implemented.

**Comment by HyeockJinKim** [comment]
## Functions to export from @0auth/server.
All function names and type names can be changed. Currently they are named arbitrarily.

* ```javascript
  function auth_privacy(properties: Property[], secret: SecretKey): Signature {
    // TODO: Not implemented yet.
  }
  function auth_package(properties: Property[], secret: SecretKey): Signature {
    // TODO: Not implemented yet.
  }
  ```
    - Functions that authenticate the client's value on the server.
    - `auth_privacy` creates a Hash Tree and signs the root Hash value. Therefore, signature verification is possible even if some values are not revealed.
    - `auth_package` is used to sign a bundle hash when the values are used together.

* ```javascript
  function verify_privacy(properties: Property[], sign: Signature, public: PublicKey): boolean {
    // TODO: Not implemented yet.
  }
  function verify_package(properties: Property[], sign: Signature, public: PublicKey): boolean {
    // TODO: Not implemented yet.
  }
  ```
    - Functions to check if the value is signed.
    - After generating the Hash value for each authentication method, verify the signature.

**Comment by HyeockJinKim** [comment]
## Types to export from @0auth/client.
All function names and type names can be changed. Currently they are named arbitrarily.

* ```typescript
  enum PropertyType {
    Row,
    Hash,
  }
  ```
    - Type used to distinguish between the regular value and the hash value.

* ```typescript
  type Property = {
    typ: PropertyType;
    val: string
  }
  ```
    - A type for client information.

* ```typescript
  enum AuthType {
    Privacy,
    Package,
    Local,
  }
  ```
    - A type that checks which authentication method the client's information uses.

* ```typescript
  type Signature = {
    typ: AuthType;
    val: string
  }
  ```
    - A type for server's signature.

**Comment by HyeockJinKim** [comment]
@anthonyminyungi Please review the above.
If there is no problem, I will make the above skeleton.

**Comment by anthonyminyungi** [comment]
Reviews and questions.

1. Let's use the name of functions and variables to `camelCase`. Because it has better readability and used broadly on the Javascript ecosystem.

2. The key named `typ` on `Property` and `Signature` is intended? I think the shortened words are not good for readability. Let's change'em `type` and `value`.

3. The types are only declared in `@0auth/client`?

For others, LGTM.

**Comment by HyeockJinKim** [comment]
@anthonyminyungi 
1. I will write it as 'camelCase'.

2. It is my mistake. When the variable name is written as `type`, there is a problem of overlapping with the type keyword, but this problem does not exist in the type internal value.

3. I wrote it as a client by mistake, but it is a `message`.
