### ISSUE TITLE
Implement the function to store the encrypted value in indexeddb or localStorage.

### ISSUE THREAD

**Issue by HyeockJinKim** [0-Auth/0Auth#17]
## Feature Request

It is dangerous to store signature data and user data as raw values. 
Therefore, it should support the function to encrypt and store this value.

Data can be encrypted and decrypted again using AES encryption. 

https://github.com/0-Auth/0Auth/blob/b85bfec96e044991414de6100dd0495613e269da/packages/client/src/index.ts#L9-L11

**However, the problem is how to manage the key.**

If the user loses the key, all stored data cannot be used.
It is necessary to discuss key management.

**Is your feature request related to a problem? Please describe.**  

It is dangerous to store user data and signature values as raw values.

**Describe the solution you'd like**  

User data and signature are encrypted and stored through AES encryption.

**Describe alternatives you've considered**  

**Additional context**

**Comment by anthonyminyungi** [comment]
Let's discuss this issue tomorrow in offline.
