### ISSUE TITLE
Code refactoring for server package 

### ISSUE THREAD

**Issue by HyeockJinKim** [0-Auth/0Auth#34]
## Feature Request

**Is your feature request related to a problem? Please describe.**  

~~The name of the function or variable of the currently written code should be changed to make it simpler.~~

**Describe the solution you'd like**  

~~We need to make it simple for the currently written functions and variables, and make lint all pass.~~
Split the code into the separated directory followed by the feature of each function of the `server` package.

**Describe alternatives you've considered**  

**Additional context**

**Comment by anthonyminyungi** [comment]
Key requirements:
- Fix formatting
- Stabilize ESLint
